apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrate
      labels:
        service: migrate
    spec:
      initContainers:
        - name: wait-for-db
          image: ghcr.io/groundnuty/k8s-wait-for:v1.6
          imagePullPolicy: Always
          args:
            - "pod"
            - "-lservice=database"
      containers:
        - name: migrate
          image: registry.gitlab.com/klavionik/cutto/backend:v1.0.7
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: secret
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: broker_url
                  name: secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: secret
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: config
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: allowed_hosts
                  name: config
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: csrf_trusted_origins
                  name: config
      restartPolicy: Never
