apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: cutto
  labels:
    service: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker
  template:
    metadata:
      labels:
        service: worker
    spec:
      initContainers:
        - name: wait-for-migration
          image: ghcr.io/groundnuty/k8s-wait-for:v1.6
          imagePullPolicy: IfNotPresent
          args:
            - "job"
            - "-lservice=migrate"
        - name: wait-for-broker
          image: ghcr.io/groundnuty/k8s-wait-for:v1.6
          imagePullPolicy: IfNotPresent
          args:
            - "pod"
            - "-lservice=broker"
      containers:
        - name: worker
          image: registry.gitlab.com/klavionik/cutto/backend
          command:
            - python
            - -m
            - celery
            - --app
            - project
            - worker
            - --beat
            - --scheduler
            - django
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: secret
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: broker_url
                  name: secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: secret
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: config
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: allowed_hosts
                  name: config
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: csrf_trusted_origins
                  name: config
