services:
  frontend:
    build:
      context: frontend
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - web

  web:
    build:
      context: backend
    command:
      - "gunicorn"
      - "--reload"
      - "--bind"
      - "0.0.0.0:8000"
      - "--workers"
      - "2"
      - "project.wsgi:application"
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - web
      - worker
      - db

  worker:
    build:
      context: backend
    depends_on:
      broker:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    command: ["python", "-m", "celery", "--app", "project", "worker", "--beat", "--scheduler", "django"]
    networks:
      - worker
      - db
    volumes:
      - ./backend:/app

  broker:
    image: rabbitmq:3.8-alpine
    hostname: broker
    networks:
      - worker

  db:
    image: postgres:14.5-alpine
    env_file:
      - .env
    healthcheck:
      test: pg_isready --username $POSTGRES_USER || exit 1
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db

  migrate:
    build:
      context: backend
    command: ["python", "manage.py", "migrate"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

volumes:
  db_data:
  caddy_data:

networks:
  web:
  db:
  worker:
