services:
  web:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - DATABASE_URL
    ports:
      - "8010:8000"
    volumes:
      - ./:/app

  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: pg_isready --username $POSTGRES_USER || exit 1
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
