services:
  frontend:
    build:
      context: frontend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  web:
    build:
      context: backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app

  db:
    image: postgres:14.5-alpine
    env_file:
      - .env
    healthcheck:
      test: pg_isready --username $POSTGRES_USER || exit 1
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  caddy_data:
