# https://taskfile.dev

version: '3'

tasks:
  flake8:
    cmds:
      - pre-commit run flake8 --all-files

  black:
    cmds:
      - pre-commit run black --all-files

  isort:
    cmds:
      - pre-commit run isort --all-files

  lint.backend:
    cmds:
      - task: isort
      - task: black
      - task: flake8

  build:
    cmds:
      - docker compose build

  up:
    cmds:
      - docker compose up -d

  pyshell:
    cmds:
      - docker compose exec backend python manage.py shell

  shell:
    cmds:
      - docker compose exec backend bash

  logs.backend:
    cmds:
      - docker compose logs backend

  makemigrations:
    cmds:
      - docker compose exec backend python manage.py makemigrations

  migrate:
    cmds:
      - docker compose exec backend python manage.py migrate

  createsu:
    cmds:
      - docker compose exec backend python manage.py createsuperuser

  reload.caddy:
    cmds:
      - docker compose exec -w /etc/caddy frontend caddy reload

  fmt.caddy:
    cmds:
      - docker compose exec -w /etc/caddy frontend caddy fmt Caddyfile --overwrite

  logs.worker:
    cmds:
      - docker compose logs -f worker

  down:
    cmds:
      - docker compose down -v

  ps:
    cmds:
      - docker compose ps -a

  deploy.local:
    cmds:
      - kubectl apply -k deploy/manifests/local
