# https://taskfile.dev

version: '3'

tasks:
  flake8:
    cmds:
      - pre-commit run flake8 --all-files

  black:
    cmds:
      - pre-commit run black --all-files

  isort:
    cmds:
      - pre-commit run isort --all-files

  lint:
    cmds:
      - task: isort
      - task: black
      - task: flake8

  build:
    cmds:
      - docker compose build

  up:
    cmds:
      - docker compose up -d

  pyshell:
    cmds:
      - docker compose exec web python manage.py shell

  shell:
    cmds:
      - docker compose exec web bash

  logs.web:
    cmds:
      - docker compose logs web

  makemigrations:
    cmds:
      - docker compose exec web python manage.py makemigrations

  migrate:
    cmds:
      - docker compose exec web python manage.py migrate