name: Build Docker image
description: Build Docker image for a given service and push it to ghcr.io
inputs:
  service:
    description: Name of the service to build
    required: true
  context:
    description: Path to the Dockerfile context
    default: .
runs:
  using: "composite"
  steps:
    - name: Extract Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.service }}

    - name: Login to GitHub CR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
