apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: database
  name: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      service: database
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
        - name: database
          image: postgres:14.5-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_password
                  name: secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: database_user
                  name: secret
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: database_name
                  name: config
          livenessProbe:
            exec:
              command:
                - pg_isready --username $POSTGRES_USER || exit 1
            failureThreshold: 5
            periodSeconds: 3
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    service: database
  ports:
    - port: 5432
