# Generated by Django 4.1.7 on 2023-03-28 11:36

from django.db import migrations
from django_celery_beat.models import IntervalSchedule, PeriodicTask


def add_default_delete_expired_links_task(*_args):
    interval, _ = IntervalSchedule.objects.get_or_create(every=1, period=IntervalSchedule.MINUTES)
    PeriodicTask.objects.create(
        name='Delete expired links',
        task='shortener.tasks.delete_expired_links',
        interval=interval,
    )


def remove_default_delete_expired_links_task(*_args):
    PeriodicTask.objects.filter(task='shortener.tasks.delete_expired_links').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext')
    ]

    operations = [
        migrations.RunPython(
            add_default_delete_expired_links_task,
            reverse_code=remove_default_delete_expired_links_task,
        )
    ]
