apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cutto-ingress
spec:
  rules:
    - host: cutto.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
