name: Build app images
run-name: Build version ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"

jobs:
  build-frontend:
    name: Build frontend service
    runs-on: [self-hosted, arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: Klavionik/gh-actions/build-image@main
        name: Build
        with:
          context: frontend
          service: frontend
          cache-access-key: ${{ secrets.S3_ACCESS_KEY }}
          cache-secret-key: ${{ secrets.S3_SECRET_KEY }}
          cache-bucket: cutto-build-cache

  build-backend:
    name: Build backend service
    runs-on: [self-hosted, arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: Klavionik/gh-actions/build-image@main
        name: Build
        with:
          context: backend
          service: backend
