name: Build app images
run-name: Build version ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"

env:
  S3_BUCKET: cutto-build-cache
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

jobs:
  build-frontend:
    name: Build frontend service
    runs-on: [self-hosted, arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: Klavionik/gh-actions/build-image@main
        name: Build
        with:
          context: frontend
          service: frontend

  build-backend:
    name: Build backend service
    runs-on: [self-hosted, arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: Klavionik/gh-actions/build-image@main
        name: Build
        with:
          context: backend
          service: backend
