name: Build app images
run-name: Build app v${{ github.ref_name }}

on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: ./.github/actions/build-image@main
        name: Build frontend image
        with:
          context: frontend
          service: frontend

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: ./.github/actions/build-image@main
        name: Build backend image
        with:
          context: backend
          service: backend
