name: Build app images
run-name: Build app v${{ github.ref_name }}

on:
  push:
    tags:
      - "*"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/build-image@main
        with:
          context: frontend
          service: frontend

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/build-image@main
        with:
          context: backend
          service: backend
